version: '3'

services:

  app:
    build: ./
    container_name: 'rentMe-app'
    ports:
      - "8080:8080"
    networks:
      - postgres
      - spring
    restart: unless-stopped

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_DB=rentme'
      - 'POSTGRES_DB=rentme_account'
    volumes:
      - postgres:/var/lib/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge