package application.business.dto1;

public enum NameOfAmentity
{
	ELEVATOR, WASHER_IN_UNIT, CHILDREN_ALLOWED, PARKING_SPOT, BALCONY, GARDEN, TERRACE, AIR_CONDITIONING, DISHWASHER,
	VIEW, PET_FRIENDLY, UNFURNISHED
}
